name: Deploy Next.js to cPanel

on:
  push:
    branches:
      - main # Adjust to your default branch

jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Use your project's Node.js version

    - name: Install Dependencies
      run: npm install --legacy-peer-deps # Use 'npm install' if you're not using Yarn

    - name: Build and Export Static Files
      run: npm run build # Ensure this runs `next build` and `next export`

    - name: Deploy to cPanel
      env:
        CPANEL_USERNAME: ${{ secrets.FTP_USER }}
        CPANEL_PASSWORD: ${{ secrets.FTP_PASS }}
        CPANEL_SERVER: ${{ secrets.FTP_SERVER }}
      run: |
        # Install lftp for file transfer
        sudo apt-get install lftp
        # Upload the exported static files to cPanel public_html directory
        lftp -u "$CPANEL_USERNAME,$CPANEL_PASSWORD" "$CPANEL_SERVER" -e "
        mirror -R ./out /public_html;
        bye"